name: Deploy Examples

on:
  push:
    branches:
      - main

jobs:
  deploy-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install GNU make, xmllint, and xsltproc
        run: sudo apt-get update && sudo apt-get install make libxml2-utils xsltproc -y

      - name: Build
        run: make -C ./example/html clean index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./example/html/
          destination_dir: ./html
